open Emoji

let reproduce_emoji s = 
  match s with 
  | "grinning_face" -> Emoji.grinning_face
  | "grinning_face_with_smiling_eyes" -> Emoji.grinning_face_with_smiling_eyes
  | "rolling_on_the_floor_laughing" -> Emoji.rolling_on_the_floor_laughing
  | "face_with_tears_of_joy" -> Emoji.face_with_tears_of_joy
  | "slightly_smiling_face" -> Emoji.slightly_smiling_face
  | "upside-down_face" -> Emoji.upside_down_face
  | "winking_face" -> Emoji.winking_face
  | "smiling_face_with_smiling_eyes" -> Emoji.smiling_face_with_smiling_eyes
  | "smiling_face_with_halo" -> Emoji.smiling_face_with_halo
  | "smiling_face_with_heart-eyes" -> Emoji.smiling_face_with_heart_eyes
  | "face_blowing_a_kiss" -> Emoji.face_blowing_a_kiss
  | "kissing_face" -> Emoji.kissing_face
  | "smiling_face" -> Emoji.smiling_face
  | "kissing_face_with_closed_eyes" -> Emoji.kissing_face_with_closed_eyes
  | "kissing_face_with_smiling_eyes" -> Emoji.kissing_face_with_smiling_eyes
  | "thinking_face" -> Emoji.thinking_face
  | "zipper-mouth_face" -> Emoji.zipper_mouth_face
  | "neutral_face" -> Emoji.neutral_face
  | "expressionless_face" -> Emoji.expressionless_face
  | "face_without_mouth" -> Emoji.face_without_mouth
  | "smirking_face" -> Emoji.smirking_face
  | "unamused_face" -> Emoji.unamused_face
  | "face_with_rolling_eyes" -> Emoji.face_with_rolling_eyes
  | "grimacing_face" -> Emoji.grimacing_face
  | "lying_face" -> Emoji.lying_face
  | "relieved_face" -> Emoji.relieved_face
  | "pensive_face" -> Emoji.pensive_face
  | "sleepy_face" -> Emoji.sleepy_face
  | "drooling_face" -> Emoji.drooling_face
  | "sleeping_face" -> Emoji.sleeping_face
  | "face_with_medical_mask" -> Emoji.face_with_medical_mask
  | "face_with_thermometer" -> Emoji.face_with_thermometer
  | "face_with_head-bandage" -> Emoji.face_with_head_bandage
  | "nauseated_face" -> Emoji.nauseated_face
  | "sneezing_face" -> Emoji.sneezing_face
  | "cowboy_hat_face" -> Emoji.cowboy_hat_face
  | "smiling_face_with_sunglasses" -> Emoji.smiling_face_with_sunglasses
  | "nerd_face" -> Emoji.nerd_face
  | "confused_face" -> Emoji.confused_face
  | "worried_face" -> Emoji.worried_face
  | "slightly_frowning_face" -> Emoji.slightly_frowning_face
  | "frowning_face" -> Emoji.frowning_face
  | "face_with_open_mouth" -> Emoji.face_with_open_mouth
  | "hushed_face" -> Emoji.hushed_face
  | "astonished_face" -> Emoji.astonished_face
  | "flushed_face" -> Emoji.flushed_face
  | "frowning_face_with_open_mouth" -> Emoji.frowning_face_with_open_mouth
  | "anguished_face" -> Emoji.anguished_face
  | "fearful_face" -> Emoji.fearful_face
  | "crying_face" -> Emoji.crying_face
  | "loudly_crying_face" -> Emoji.loudly_crying_face
  | "face_screaming_in_fear" -> Emoji.face_screaming_in_fear
  | "confounded_face" -> Emoji.confounded_face
  | "persevering_face" -> Emoji.persevering_face
  | "disappointed_face" -> Emoji.disappointed_face
  | "weary_face" -> Emoji.weary_face
  | "tired_face" -> Emoji.tired_face
  | "face_with_steam_from_nose" -> Emoji.face_with_steam_from_nose
  | "pouting_face" -> Emoji.pouting_face
  | "angry_face" -> Emoji.angry_face
  | "smiling_face_with_horns" -> Emoji.smiling_face_with_horns
  | "angry_face_with_horns" -> Emoji.angry_face_with_horns
  | "skull" -> Emoji.skull
  | "skull_and_crossbones" -> Emoji.skull_and_crossbones
  | "pile_of_poo" -> Emoji.pile_of_poo
  | "clown_face" -> Emoji.clown_face
  | "ogre" -> Emoji.ogre
  | "goblin" -> Emoji.goblin
  | "ghost" -> Emoji.ghost
  | "alien" -> Emoji.alien
  | "alien_monster" -> Emoji.alien_monster
  | "kiss_mark" -> Emoji.kiss_mark
  | "love_letter" -> Emoji.love_letter
  | "heart_with_arrow" -> Emoji.heart_with_arrow
  | "heart_with_ribbon" -> Emoji.heart_with_ribbon
  | "sparkling_heart" -> Emoji.sparkling_heart
  | "growing_heart" -> Emoji.growing_heart
  | "beating_heart" -> Emoji.beating_heart
  | "revolving_hearts" -> Emoji.revolving_hearts
  | "two_hearts" -> Emoji.two_hearts
  | "heart_decoration" -> Emoji.heart_decoration
  | "broken_heart" -> Emoji.broken_heart
  | "red_heart" -> Emoji.red_heart
  | "yellow_heart" -> Emoji.yellow_heart
  | "green_heart" -> Emoji.green_heart
  | "blue_heart" -> Emoji.blue_heart
  | "purple_heart" -> Emoji.purple_heart
  | "black_heart" -> Emoji.black_heart
  | "hundred_points" -> Emoji.hundred_points
  | "anger_symbol" -> Emoji.anger_symbol
  | "collision" -> Emoji.collision
  | "dizzy" -> Emoji.dizzy
  | "sweat_droplets" -> Emoji.sweat_droplets
  | "dashing_away" -> Emoji.dashing_away
  | "hole" -> Emoji.hole
  | "bomb" -> Emoji.bomb
  | "speech_balloon" -> Emoji.speech_balloon
  | "eye_in_speech_bubble" -> Emoji.eye_in_speech_bubble
  | "left_speech_bubble" -> Emoji.left_speech_bubble
  | "right_anger_bubble" -> Emoji.right_anger_bubble
  | "thought_balloon" -> Emoji.thought_balloon
  | "zzz" -> Emoji.zzz
  | "waving_hand" -> Emoji.waving_hand
  | "raised_back_of_hand" -> Emoji.raised_back_of_hand
  | "raised_hand" -> Emoji.raised_hand
  | "vulcan_salute" -> Emoji.vulcan_salute
  | "ok_hand" -> Emoji.ok_hand
  | "victory_hand" -> Emoji.victory_hand
  | "crossed_fingers" -> Emoji.crossed_fingers
  | "sign_of_the_horns" -> Emoji.sign_of_the_horns
  | "call_me_hand" -> Emoji.call_me_hand
  | "backhand_index_pointing_left" -> Emoji.backhand_index_pointing_left
  | "backhand_index_pointing_right" -> Emoji.backhand_index_pointing_right
  | "backhand_index_pointing_up" -> Emoji.backhand_index_pointing_up
  | "middle_finger" -> Emoji.middle_finger
  | "backhand_index_pointing_down" -> Emoji.backhand_index_pointing_down
  | "index_pointing_up" -> Emoji.index_pointing_up
  | "thumbs_up" -> Emoji.thumbs_up
  | "thumbs_down" -> Emoji.thumbs_down
  | "raised_fist" -> Emoji.raised_fist
  | "oncoming_fist" -> Emoji.oncoming_fist
  | "clapping_hands" -> Emoji.clapping_hands
  | "raising_hands" -> Emoji.raising_hands
  | "open_hands" -> Emoji.open_hands
  | "handshake" -> Emoji.handshake
  | "folded_hands" -> Emoji.folded_hands
  | "writing_hand" -> Emoji.writing_hand
  | "nail_polish" -> Emoji.nail_polish
  | "selfie" -> Emoji.selfie
  | "flexed_biceps" -> Emoji.flexed_biceps
  | "eyes" -> Emoji.eyes
  | "eye" -> Emoji.eye
  | "tongue" -> Emoji.tongue
  | "mouth" -> Emoji.mouth
  | "baby" -> Emoji.baby
  | "boy" -> Emoji.boy
  | "girl" -> Emoji.girl
  | "man" -> Emoji.man
  | "old_man" -> Emoji.old_man
  | "old_woman" -> Emoji.old_woman
  | "person_frowning" -> Emoji.person_frowning
  | "man_frowning" -> Emoji.man_frowning
  | "woman_frowning" -> Emoji.woman_frowning
  | "person_pouting" -> Emoji.person_pouting
  | "man_pouting" -> Emoji.man_pouting
  | "woman_pouting" -> Emoji.woman_pouting
  | "person_gesturing_no" -> Emoji.person_gesturing_no
  | "man_gesturing_no" -> Emoji.man_gesturing_no
  | "woman_gesturing_no" -> Emoji.woman_gesturing_no
  | "person_gesturing_ok" -> Emoji.person_gesturing_ok
  | "man_gesturing_ok" -> Emoji.man_gesturing_ok
  | "woman_gesturing_ok" -> Emoji.woman_gesturing_ok
  | "person_tipping_hand" -> Emoji.person_tipping_hand
  | "man_tipping_hand" -> Emoji.man_tipping_hand
  | "woman_tipping_hand" -> Emoji.woman_tipping_hand
  | "person_raising_hand" -> Emoji.person_raising_hand
  | "man_raising_hand" -> Emoji.man_raising_hand
  | "woman_raising_hand" -> Emoji.woman_raising_hand
  | "person_bowing" -> Emoji.person_bowing
  | "man_bowing" -> Emoji.man_bowing
  | "woman_bowing" -> Emoji.woman_bowing
  | "person_facepalming" -> Emoji.person_facepalming
  | "man_facepalming" -> Emoji.man_facepalming
  | "woman_facepalming" -> Emoji.woman_facepalming
  | "person_shrugging" -> Emoji.person_shrugging
  | "man_shrugging" -> Emoji.man_shrugging
  | "woman_shrugging" -> Emoji.woman_shrugging
  | "man_health_worker" -> Emoji.man_health_worker
  | "woman_health_worker" -> Emoji.woman_health_worker
  | "man_student" -> Emoji.man_student
  | "woman_student" -> Emoji.woman_student
  | "man_teacher" -> Emoji.man_teacher
  | "woman_teacher" -> Emoji.woman_teacher
  | "man_judge" -> Emoji.man_judge
  | "woman_judge" -> Emoji.woman_judge
  | "man_farmer" -> Emoji.man_farmer
  | "woman_farmer" -> Emoji.woman_farmer
  | "man_cook" -> Emoji.man_cook
  | "woman_cook" -> Emoji.woman_cook
  | "man_mechanic" -> Emoji.man_mechanic
  | "woman_mechanic" -> Emoji.woman_mechanic
  | "man_factory_worker" -> Emoji.man_factory_worker
  | "woman_factory_worker" -> Emoji.woman_factory_worker
  | "man_office_worker" -> Emoji.man_office_worker
  | "woman_office_worker" -> Emoji.woman_office_worker
  | "man_scientist" -> Emoji.man_scientist
  | "man_technologist" -> Emoji.man_technologist
  | "woman_technologist" -> Emoji.woman_technologist
  | "man_singer" -> Emoji.man_singer
  | "woman_singer" -> Emoji.woman_singer
  | "man_artist" -> Emoji.man_artist
  | "woman_artist" -> Emoji.woman_artist
  | "man_pilot" -> Emoji.man_pilot
  | "woman_pilot" -> Emoji.woman_pilot
  | "man_astronaut" -> Emoji.man_astronaut
  | "woman_astronaut" -> Emoji.woman_astronaut
  | "man_firefighter" -> Emoji.man_firefighter
  | "woman_firefighter" -> Emoji.woman_firefighter
  | "police_officer" -> Emoji.police_officer
  | "man_police_officer" -> Emoji.man_police_officer
  | "woman_police_officer" -> Emoji.woman_police_officer
  | "detective" -> Emoji.detective
  | "man_detective" -> Emoji.man_detective
  | "woman_detective" -> Emoji.woman_detective
  | "guard" -> Emoji.guard
  | "man_guard" -> Emoji.man_guard
  | "woman_guard" -> Emoji.woman_guard
  | "construction_worker" -> Emoji.construction_worker
  | "man_construction_worker" -> Emoji.man_construction_worker
  | "woman_construction_worker" -> Emoji.woman_construction_worker
  | "prince" -> Emoji.prince
  | "princess" -> Emoji.princess
  | "person_wearing_turban" -> Emoji.person_wearing_turban
  | "man_wearing_turban" -> Emoji.man_wearing_turban
  | "woman_wearing_turban" -> Emoji.woman_wearing_turban
  | "man_in_tuxedo" -> Emoji.man_in_tuxedo
  | "bride_with_veil" -> Emoji.bride_with_veil
  | "pregnant_woman" -> Emoji.pregnant_woman
  | "baby_angel" -> Emoji.baby_angel
  | "santa_claus" -> Emoji.santa_claus
  | "person_getting_massage" -> Emoji.person_getting_massage
  | "man_getting_massage" -> Emoji.man_getting_massage
  | "woman_getting_massage" -> Emoji.woman_getting_massage
  | "person_getting_haircut" -> Emoji.person_getting_haircut
  | "man_getting_haircut" -> Emoji.man_getting_haircut
  | "woman_getting_haircut" -> Emoji.woman_getting_haircut
  | "person_walking" -> Emoji.person_walking
  | "man_walking" -> Emoji.man_walking
  | "woman_walking" -> Emoji.woman_walking
  | "person_running" -> Emoji.person_running
  | "man_running" -> Emoji.man_running
  | "woman_running" -> Emoji.woman_running
  | "woman_dancing" -> Emoji.woman_dancing
  | "man_dancing" -> Emoji.man_dancing
  | "person_golfing" -> Emoji.person_golfing
  | "man_golfing" -> Emoji.man_golfing
  | "woman_golfing" -> Emoji.woman_golfing
  | "person_surfing" -> Emoji.person_surfing
  | "man_surfing" -> Emoji.man_surfing
  | "woman_surfing" -> Emoji.woman_surfing
  | "person_rowing_boat" -> Emoji.person_rowing_boat
  | "man_rowing_boat" -> Emoji.man_rowing_boat
  | "woman_rowing_boat" -> Emoji.woman_rowing_boat
  | "person_swimming" -> Emoji.person_swimming
  | "man_swimming" -> Emoji.man_swimming
  | "woman_swimming" -> Emoji.woman_swimming
  | "person_bouncing_ball" -> Emoji.person_bouncing_ball
  | "man_bouncing_ball" -> Emoji.man_bouncing_ball
  | "woman_bouncing_ball" -> Emoji.woman_bouncing_ball
  | "person_lifting_weights" -> Emoji.person_lifting_weights
  | "man_lifting_weights" -> Emoji.man_lifting_weights
  | "woman_lifting_weights" -> Emoji.woman_lifting_weights
  | "person_biking" -> Emoji.person_biking
  | "man_biking" -> Emoji.man_biking
  | "woman_biking" -> Emoji.woman_biking
  | "person_mountain_biking" -> Emoji.person_mountain_biking
  | "man_mountain_biking" -> Emoji.man_mountain_biking
  | "woman_mountain_biking" -> Emoji.woman_mountain_biking
  | "person_cartwheeling" -> Emoji.person_cartwheeling
  | "man_cartwheeling" -> Emoji.man_cartwheeling
  | "woman_cartwheeling" -> Emoji.woman_cartwheeling
  | "people_wrestling" -> Emoji.people_wrestling
  | "men_wrestling" -> Emoji.men_wrestling
  | "women_wrestling" -> Emoji.women_wrestling
  | "person_playing_water_polo" -> Emoji.person_playing_water_polo
  | "man_playing_water_polo" -> Emoji.man_playing_water_polo
  | "woman_playing_water_polo" -> Emoji.woman_playing_water_polo
  | "person_playing_handball" -> Emoji.person_playing_handball
  | "man_playing_handball" -> Emoji.man_playing_handball
  | "woman_playing_handball" -> Emoji.woman_playing_handball
  | "person_juggling" -> Emoji.person_juggling
  | "man_juggling" -> Emoji.man_juggling
  | "woman_juggling" -> Emoji.woman_juggling
  | "person_taking_bath" -> Emoji.person_taking_bath
  | "person_in_bed" -> Emoji.person_in_bed
  | "kiss" -> Emoji.kiss
  | "kiss:_woman,_man" -> Emoji.kiss_woman_man
  | "kiss:_man,_man" -> Emoji.kiss_man_man
  | "kiss:_woman,_woman" -> Emoji.kiss_woman_woman
  | "couple_with_heart" -> Emoji.couple_with_heart
  | "couple_with_heart:_woman,_man" -> Emoji.couple_with_heart_woman_man
  | "couple_with_heart:_man,_man" -> Emoji.couple_with_heart_man_man
  | "couple_with_heart:_woman,_woman" -> Emoji.couple_with_heart_woman_woman
  | "family" -> Emoji.family
  | "speaking_head" -> Emoji.speaking_head
  | "bust_in_silhouette" -> Emoji.bust_in_silhouette
  | "busts_in_silhouette" -> Emoji.busts_in_silhouette
  | "footprints" -> Emoji.footprints
  | "monkey_face" -> Emoji.monkey_face
  | "monkey" -> Emoji.monkey
  | "gorilla" -> Emoji.gorilla
  | "dog_face" -> Emoji.dog_face
  | "dog" -> Emoji.dog
  | "cat" -> Emoji.cat
  | "tiger_face" -> Emoji.tiger_face
  | "tiger" -> Emoji.tiger
  | "leopard" -> Emoji.leopard
  | "horse_face" -> Emoji.horse_face
  | "horse" -> Emoji.horse
  | "deer" -> Emoji.deer
  | "cow_face" -> Emoji.cow_face
  | "ox" -> Emoji.ox
  | "water_buffalo" -> Emoji.water_buffalo
  | "cow" -> Emoji.cow
  | "pig_face" -> Emoji.pig_face
  | "pig" -> Emoji.pig
  | "boar" -> Emoji.boar
  | "pig_nose" -> Emoji.pig_nose
  | "ram" -> Emoji.ram
  | "goat" -> Emoji.goat
  | "camel" -> Emoji.camel
  | "elephant" -> Emoji.elephant
  | "rhinoceros" -> Emoji.rhinoceros
  | "bat" -> Emoji.bat
  | "koala" -> Emoji.koala
  | "chicken" -> Emoji.chicken
  | "rooster" -> Emoji.rooster
  | "hatching_chick" -> Emoji.hatching_chick
  | "baby_chick" -> Emoji.baby_chick
  | "front-facing_baby_chick" -> Emoji.front_facing_baby_chick
  | "bird" -> Emoji.bird
  | "penguin" -> Emoji.penguin
  | "dove" -> Emoji.dove
  | "eagle" -> Emoji.eagle
  | "duck" -> Emoji.duck
  | "owl" -> Emoji.owl
  | "crocodile" -> Emoji.crocodile
  | "turtle" -> Emoji.turtle
  | "lizard" -> Emoji.lizard
  | "snake" -> Emoji.snake
  | "dragon_face" -> Emoji.dragon_face
  | "dragon" -> Emoji.dragon
  | "spouting_whale" -> Emoji.spouting_whale
  | "whale" -> Emoji.whale
  | "dolphin" -> Emoji.dolphin
  | "fish" -> Emoji.fish
  | "tropical_fish" -> Emoji.tropical_fish
  | "blowfish" -> Emoji.blowfish
  | "shark" -> Emoji.shark
  | "octopus" -> Emoji.octopus
  | "spiral_shell" -> Emoji.spiral_shell
  | "snail" -> Emoji.snail
  | "butterfly" -> Emoji.butterfly
  | "bug" -> Emoji.bug
  | "ant" -> Emoji.ant
  | "honeybee" -> Emoji.honeybee
  | "lady_beetle" -> Emoji.lady_beetle
  | "cricket" -> Emoji.cricket
  | "spider" -> Emoji.spider
  | "spider_web" -> Emoji.spider_web
  | "scorpion" -> Emoji.scorpion
  | "bouquet" -> Emoji.bouquet
  | "cherry_blossom" -> Emoji.cherry_blossom
  | "white_flower" -> Emoji.white_flower
  | "rosette" -> Emoji.rosette
  | "rose" -> Emoji.rose
  | "wilted_flower" -> Emoji.wilted_flower
  | "hibiscus" -> Emoji.hibiscus
  | "sunflower" -> Emoji.sunflower
  | "blossom" -> Emoji.blossom
  | "tulip" -> Emoji.tulip
  | "seedling" -> Emoji.seedling
  | "evergreen_tree" -> Emoji.evergreen_tree
  | "deciduous_tree" -> Emoji.deciduous_tree
  | "palm_tree" -> Emoji.palm_tree
  | "cactus" -> Emoji.cactus
  | "sheaf_of_rice" -> Emoji.sheaf_of_rice
  | "herb" -> Emoji.herb
  | "shamrock" -> Emoji.shamrock
  | "four_leaf_clover" -> Emoji.four_leaf_clover
  | "maple_leaf" -> Emoji.maple_leaf
  | "fallen_leaf" -> Emoji.fallen_leaf
  | "leaf_fluttering_in_wind" -> Emoji.leaf_fluttering_in_wind
  | "grapes" -> Emoji.grapes
  | "melon" -> Emoji.melon
  | "watermelon" -> Emoji.watermelon
  | "tangerine" -> Emoji.tangerine
  | "lemon" -> Emoji.lemon
  | "banana" -> Emoji.banana
  | "pineapple" -> Emoji.pineapple
  | "red_apple" -> Emoji.red_apple
  | "green_apple" -> Emoji.green_apple
  | "pear" -> Emoji.pear
  | "peach" -> Emoji.peach
  | "cherries" -> Emoji.cherries
  | "strawberry" -> Emoji.strawberry
  | "kiwi_fruit" -> Emoji.kiwi_fruit
  | "tomato" -> Emoji.tomato
  | "avocado" -> Emoji.avocado
  | "eggplant" -> Emoji.eggplant
  | "potato" -> Emoji.potato
  | "carrot" -> Emoji.carrot
  | "ear_of_corn" -> Emoji.ear_of_corn
  | "hot_pepper" -> Emoji.hot_pepper
  | "cucumber" -> Emoji.cucumber
  | "pizza" -> Emoji.pizza
  | "hot_dog" -> Emoji.hot_dog
  | "taco" -> Emoji.taco
  | "burrito" -> Emoji.burrito
  | "stuffed_flatbread" -> Emoji.stuffed_flatbread
  | "egg" -> Emoji.egg
  | "cooking" -> Emoji.cooking
  | "shallow_pan_of_food" -> Emoji.shallow_pan_of_food
  | "pot_of_food" -> Emoji.pot_of_food
  | "green_salad" -> Emoji.green_salad
  | "popcorn" -> Emoji.popcorn
  | "cooked_rice" -> Emoji.cooked_rice
  | "curry_rice" -> Emoji.curry_rice
  | "steaming_bowl" -> Emoji.steaming_bowl
  | "spaghetti" -> Emoji.spaghetti
  | "roasted_sweet_potato" -> Emoji.roasted_sweet_potato
  | "oden" -> Emoji.oden
  | "sushi" -> Emoji.sushi
  | "fried_shrimp" -> Emoji.fried_shrimp
  | "fish_cake_with_swirl" -> Emoji.fish_cake_with_swirl
  | "dango" -> Emoji.dango
  | "soft_ice_cream" -> Emoji.soft_ice_cream
  | "shaved_ice" -> Emoji.shaved_ice
  | "ice_cream" -> Emoji.ice_cream
  | "doughnut" -> Emoji.doughnut
  | "cookie" -> Emoji.cookie
  | "birthday_cake" -> Emoji.birthday_cake
  | "shortcake" -> Emoji.shortcake
  | "chocolate_bar" -> Emoji.chocolate_bar
  | "candy" -> Emoji.candy
  | "lollipop" -> Emoji.lollipop
  | "custard" -> Emoji.custard
  | "honey_pot" -> Emoji.honey_pot
  | "baby_bottle" -> Emoji.baby_bottle
  | "glass_of_milk" -> Emoji.glass_of_milk
  | "hot_beverage" -> Emoji.hot_beverage
  | "teacup_without_handle" -> Emoji.teacup_without_handle
  | "sake" -> Emoji.sake
  | "bottle_with_popping_cork" -> Emoji.bottle_with_popping_cork
  | "wine_glass" -> Emoji.wine_glass
  | "cocktail_glass" -> Emoji.cocktail_glass
  | "tropical_drink" -> Emoji.tropical_drink
  | "beer_mug" -> Emoji.beer_mug
  | "clinking_beer_mugs" -> Emoji.clinking_beer_mugs
  | "clinking_glasses" -> Emoji.clinking_glasses
  | "tumbler_glass" -> Emoji.tumbler_glass
  | "fork_and_knife_with_plate" -> Emoji.fork_and_knife_with_plate
  | "fork_and_knife" -> Emoji.fork_and_knife
  | "spoon" -> Emoji.spoon
  | "kitchen_knife" -> Emoji.kitchen_knife
  | "amphora" -> Emoji.amphora
  | "world_map" -> Emoji.world_map
  | "map_of_japan" -> Emoji.map_of_japan
  | "mountain" -> Emoji.mountain
  | "volcano" -> Emoji.volcano
  | "mount_fuji" -> Emoji.mount_fuji
  | "camping" -> Emoji.camping
  | "beach_with_umbrella" -> Emoji.beach_with_umbrella
  | "desert" -> Emoji.desert
  | "desert_island" -> Emoji.desert_island
  | "national_park" -> Emoji.national_park
  | "stadium" -> Emoji.stadium
  | "classical_building" -> Emoji.classical_building
  | "building_construction" -> Emoji.building_construction
  | "derelict_house" -> Emoji.derelict_house
  | "house_with_garden" -> Emoji.house_with_garden
  | "office_building" -> Emoji.office_building
  | "japanese_post_office" -> Emoji.japanese_post_office
  | "post_office" -> Emoji.post_office
  | "hospital" -> Emoji.hospital
  | "bank" -> Emoji.bank
  | "hotel" -> Emoji.hotel
  | "love_hotel" -> Emoji.love_hotel
  | "convenience_store" -> Emoji.convenience_store
  | "school" -> Emoji.school
  | "department_store" -> Emoji.department_store
  | "factory" -> Emoji.factory
  | "japanese_castle" -> Emoji.japanese_castle
  | "castle" -> Emoji.castle
  | "wedding" -> Emoji.wedding
  | "tokyo_tower" -> Emoji.tokyo_tower
  | "statue_of_liberty" -> Emoji.statue_of_liberty
  | "church" -> Emoji.church
  | "mosque" -> Emoji.mosque
  | "tent" -> Emoji.tent
  | "foggy" -> Emoji.foggy
  | "night_with_stars" -> Emoji.night_with_stars
  | "cityscape" -> Emoji.cityscape
  | "sunrise_over_mountains" -> Emoji.sunrise_over_mountains
  | "sunrise" -> Emoji.sunrise
  | "cityscape_at_dusk" -> Emoji.cityscape_at_dusk
  | "sunset" -> Emoji.sunset
  | "bridge_at_night" -> Emoji.bridge_at_night
  | "hot_springs" -> Emoji.hot_springs
  | "carousel_horse" -> Emoji.carousel_horse
  | "ferris_wheel" -> Emoji.ferris_wheel
  | "roller_coaster" -> Emoji.roller_coaster
  | "barber_pole" -> Emoji.barber_pole
  | "circus_tent" -> Emoji.circus_tent
  | "locomotive" -> Emoji.locomotive
  | "railway_car" -> Emoji.railway_car
  | "train" -> Emoji.train
  | "metro" -> Emoji.metro
  | "light_rail" -> Emoji.light_rail
  | "station" -> Emoji.station
  | "tram" -> Emoji.tram
  | "monorail" -> Emoji.monorail
  | "mountain_railway" -> Emoji.mountain_railway
  | "tram_car" -> Emoji.tram_car
  | "bus" -> Emoji.bus
  | "oncoming_bus" -> Emoji.oncoming_bus
  | "trolleybus" -> Emoji.trolleybus
  | "minibus" -> Emoji.minibus
  | "ambulance" -> Emoji.ambulance
  | "fire_engine" -> Emoji.fire_engine
  | "police_car" -> Emoji.police_car
  | "oncoming_police_car" -> Emoji.oncoming_police_car
  | "taxi" -> Emoji.taxi
  | "oncoming_taxi" -> Emoji.oncoming_taxi
  | "automobile" -> Emoji.automobile
  | "oncoming_automobile" -> Emoji.oncoming_automobile
  | "sport_utility_vehicle" -> Emoji.sport_utility_vehicle
  | "delivery_truck" -> Emoji.delivery_truck
  | "articulated_lorry" -> Emoji.articulated_lorry
  | "tractor" -> Emoji.tractor
  | "racing_car" -> Emoji.racing_car
  | "motorcycle" -> Emoji.motorcycle
  | "motor_scooter" -> Emoji.motor_scooter
  | "bicycle" -> Emoji.bicycle
  | "kick_scooter" -> Emoji.kick_scooter
  | "bus_stop" -> Emoji.bus_stop
  | "motorway" -> Emoji.motorway
  | "railway_track" -> Emoji.railway_track
  | "oil_drum" -> Emoji.oil_drum
  | "fuel_pump" -> Emoji.fuel_pump
  | "police_car_light" -> Emoji.police_car_light
  | "horizontal_traffic_light" -> Emoji.horizontal_traffic_light
  | "vertical_traffic_light" -> Emoji.vertical_traffic_light
  | "stop_sign" -> Emoji.stop_sign
  | "construction" -> Emoji.construction
  | "anchor" -> Emoji.anchor
  | "sailboat" -> Emoji.sailboat
  | "canoe" -> Emoji.canoe
  | "speedboat" -> Emoji.speedboat
  | "passenger_ship" -> Emoji.passenger_ship
  | "ferry" -> Emoji.ferry
  | "motor_boat" -> Emoji.motor_boat
  | "ship" -> Emoji.ship
  | "airplane" -> Emoji.airplane
  | "small_airplane" -> Emoji.small_airplane
  | "airplane_departure" -> Emoji.airplane_departure
  | "airplane_arrival" -> Emoji.airplane_arrival
  | "seat" -> Emoji.seat
  | "helicopter" -> Emoji.helicopter
  | "suspension_railway" -> Emoji.suspension_railway
  | "mountain_cableway" -> Emoji.mountain_cableway
  | "aerial_tramway" -> Emoji.aerial_tramway
  | "satellite" -> Emoji.satellite
  | "rocket" -> Emoji.rocket
  | "bellhop_bell" -> Emoji.bellhop_bell
  | "watch" -> Emoji.watch
  | "alarm_clock" -> Emoji.alarm_clock
  | "stopwatch" -> Emoji.stopwatch
  | "timer_clock" -> Emoji.timer_clock
  | "mantelpiece_clock" -> Emoji.mantelpiece_clock
  | "twelve_o’clock" -> Emoji.twelve_o_clock
  | "twelve-thirty" -> Emoji.twelve_thirty
  | "one_o’clock" -> Emoji.one_o_clock
  | "one-thirty" -> Emoji.one_thirty
  | "two_o’clock" -> Emoji.two_o_clock
  | "two-thirty" -> Emoji.two_thirty
  | "three_o’clock" -> Emoji.three_o_clock
  | "three-thirty" -> Emoji.three_thirty
  | "four_o’clock" -> Emoji.four_o_clock
  | "four-thirty" -> Emoji.four_thirty
  | "five_o’clock" -> Emoji.five_o_clock
  | "five-thirty" -> Emoji.five_thirty
  | "six_o’clock" -> Emoji.six_o_clock
  | "six-thirty" -> Emoji.six_thirty
  | "seven_o’clock" -> Emoji.seven_o_clock
  | "seven-thirty" -> Emoji.seven_thirty
  | "eight_o’clock" -> Emoji.eight_o_clock
  | "eight-thirty" -> Emoji.eight_thirty
  | "nine_o’clock" -> Emoji.nine_o_clock
  | "nine-thirty" -> Emoji.nine_thirty
  | "ten_o’clock" -> Emoji.ten_o_clock
  | "ten-thirty" -> Emoji.ten_thirty
  | "eleven_o’clock" -> Emoji.eleven_o_clock
  | "eleven-thirty" -> Emoji.eleven_thirty
  | "new_moon" -> Emoji.new_moon
  | "waxing_crescent_moon" -> Emoji.waxing_crescent_moon
  | "first_quarter_moon" -> Emoji.first_quarter_moon
  | "waxing_gibbous_moon" -> Emoji.waxing_gibbous_moon
  | "full_moon" -> Emoji.full_moon
  | "waning_gibbous_moon" -> Emoji.waning_gibbous_moon
  | "last_quarter_moon" -> Emoji.last_quarter_moon
  | "waning_crescent_moon" -> Emoji.waning_crescent_moon
  | "crescent_moon" -> Emoji.crescent_moon
  | "new_moon_face" -> Emoji.new_moon_face
  | "thermometer" -> Emoji.thermometer
  | "sun" -> Emoji.sun
  | "sun_with_face" -> Emoji.sun_with_face
  | "glowing_star" -> Emoji.glowing_star
  | "shooting_star" -> Emoji.shooting_star
  | "milky_way" -> Emoji.milky_way
  | "cloud" -> Emoji.cloud
  | "sun_behind_cloud" -> Emoji.sun_behind_cloud
  | "cloud_with_lightning_and_rain" -> Emoji.cloud_with_lightning_and_rain
  | "sun_behind_small_cloud" -> Emoji.sun_behind_small_cloud
  | "sun_behind_large_cloud" -> Emoji.sun_behind_large_cloud
  | "sun_behind_rain_cloud" -> Emoji.sun_behind_rain_cloud
  | "cloud_with_rain" -> Emoji.cloud_with_rain
  | "cloud_with_snow" -> Emoji.cloud_with_snow
  | "cloud_with_lightning" -> Emoji.cloud_with_lightning
  | "tornado" -> Emoji.tornado
  | "fog" -> Emoji.fog
  | "wind_face" -> Emoji.wind_face
  | "cyclone" -> Emoji.cyclone
  | "rainbow" -> Emoji.rainbow
  | "closed_umbrella" -> Emoji.closed_umbrella
  | "umbrella" -> Emoji.umbrella
  | "umbrella_with_rain_drops" -> Emoji.umbrella_with_rain_drops
  | "umbrella_on_ground" -> Emoji.umbrella_on_ground
  | "high_voltage" -> Emoji.high_voltage
  | "snowflake" -> Emoji.snowflake
  | "snowman" -> Emoji.snowman
  | "snowman_without_snow" -> Emoji.snowman_without_snow
  | "comet" -> Emoji.comet
  | "fire" -> Emoji.fire
  | "droplet" -> Emoji.droplet
  | "water_wave" -> Emoji.water_wave
  | "jack-o-lantern" -> Emoji.jack_o_lantern
  | "christmas_tree" -> Emoji.christmas_tree
  | "fireworks" -> Emoji.fireworks
  | "sparkler" -> Emoji.sparkler
  | "sparkles" -> Emoji.sparkles
  | "balloon" -> Emoji.balloon
  | "party_popper" -> Emoji.party_popper
  | "confetti_ball" -> Emoji.confetti_ball
  | "tanabata_tree" -> Emoji.tanabata_tree
  | "pine_decoration" -> Emoji.pine_decoration
  | "japanese_dolls" -> Emoji.japanese_dolls
  | "carp_streamer" -> Emoji.carp_streamer
  | "wind_chime" -> Emoji.wind_chime
  | "moon_viewing_ceremony" -> Emoji.moon_viewing_ceremony
  | "ribbon" -> Emoji.ribbon
  | "wrapped_gift" -> Emoji.wrapped_gift
  | "reminder_ribbon" -> Emoji.reminder_ribbon
  | "admission_tickets" -> Emoji.admission_tickets
  | "ticket" -> Emoji.ticket
  | "military_medal" -> Emoji.military_medal
  | "trophy" -> Emoji.trophy
  | "sports_medal" -> Emoji.sports_medal
  | "soccer_ball" -> Emoji.soccer_ball
  | "baseball" -> Emoji.baseball
  | "basketball" -> Emoji.basketball
  | "volleyball" -> Emoji.volleyball
  | "american_football" -> Emoji.american_football
  | "rugby_football" -> Emoji.rugby_football
  | "tennis" -> Emoji.tennis
  | "bowling" -> Emoji.bowling
  | "field_hockey" -> Emoji.field_hockey
  | "ice_hockey" -> Emoji.ice_hockey
  | "ping_pong" -> Emoji.ping_pong
  | "badminton" -> Emoji.badminton
  | "boxing_glove" -> Emoji.boxing_glove
  | "martial_arts_uniform" -> Emoji.martial_arts_uniform
  | "goal_net" -> Emoji.goal_net
  | "flag_in_hole" -> Emoji.flag_in_hole
  | "ice_skate" -> Emoji.ice_skate
  | "fishing_pole" -> Emoji.fishing_pole
  | "running_shirt" -> Emoji.running_shirt
  | "skis" -> Emoji.skis
  | "pool_8_ball" -> Emoji.pool_8_ball
  | "crystal_ball" -> Emoji.crystal_ball
  | "video_game" -> Emoji.video_game
  | "joystick" -> Emoji.joystick
  | "slot_machine" -> Emoji.slot_machine
  | "game_die" -> Emoji.game_die
  | "spade_suit" -> Emoji.spade_suit
  | "heart_suit" -> Emoji.heart_suit
  | "diamond_suit" -> Emoji.diamond_suit
  | "club_suit" -> Emoji.club_suit
  | "joker" -> Emoji.joker
  | "mahjong_red_dragon" -> Emoji.mahjong_red_dragon
  | "flower_playing_cards" -> Emoji.flower_playing_cards
  | "performing_arts" -> Emoji.performing_arts
  | "framed_picture" -> Emoji.framed_picture
  | "artist_palette" -> Emoji.artist_palette
  | "glasses" -> Emoji.glasses
  | "sunglasses" -> Emoji.sunglasses
  | "t-shirt" -> Emoji.t_shirt
  | "jeans" -> Emoji.jeans
  | "bikini" -> Emoji.bikini
  | "woman’s_clothes" -> Emoji.woman_s_clothes
  | "purse" -> Emoji.purse
  | "handbag" -> Emoji.handbag
  | "clutch_bag" -> Emoji.clutch_bag
  | "shopping_bags" -> Emoji.shopping_bags
  | "man’s_shoe" -> Emoji.man_s_shoe
  | "running_shoe" -> Emoji.running_shoe
  | "crown" -> Emoji.crown
  | "woman’s_hat" -> Emoji.woman_s_hat
  | "top_hat" -> Emoji.top_hat
  | "graduation_cap" -> Emoji.graduation_cap
  | "rescue_worker’s_helmet" -> Emoji.rescue_worker_s_helmet
  | "prayer_beads" -> Emoji.prayer_beads
  | "lipstick" -> Emoji.lipstick
  | "ring" -> Emoji.ring
  | "gem_stone" -> Emoji.gem_stone
  | "muted_speaker" -> Emoji.muted_speaker
  | "speaker_low_volume" -> Emoji.speaker_low_volume
  | "speaker_medium_volume" -> Emoji.speaker_medium_volume
  | "speaker_high_volume" -> Emoji.speaker_high_volume
  | "loudspeaker" -> Emoji.loudspeaker
  | "megaphone" -> Emoji.megaphone
  | "postal_horn" -> Emoji.postal_horn
  | "bell" -> Emoji.bell
  | "bell_with_slash" -> Emoji.bell_with_slash
  | "musical_score" -> Emoji.musical_score
  | "musical_note" -> Emoji.musical_note
  | "musical_notes" -> Emoji.musical_notes
  | "studio_microphone" -> Emoji.studio_microphone
  | "level_slider" -> Emoji.level_slider
  | "control_knobs" -> Emoji.control_knobs
  | "microphone" -> Emoji.microphone
  | "headphone" -> Emoji.headphone
  | "radio" -> Emoji.radio
  | "saxophone" -> Emoji.saxophone
  | "guitar" -> Emoji.guitar
  | "musical_keyboard" -> Emoji.musical_keyboard
  | "trumpet" -> Emoji.trumpet
  | "violin" -> Emoji.violin
  | "drum" -> Emoji.drum
  | "mobile_phone" -> Emoji.mobile_phone
  | "mobile_phone_with_arrow" -> Emoji.mobile_phone_with_arrow
  | "telephone" -> Emoji.telephone
  | "telephone_receiver" -> Emoji.telephone_receiver
  | "pager" -> Emoji.pager
  | "fax_machine" -> Emoji.fax_machine
  | "battery" -> Emoji.battery
  | "electric_plug" -> Emoji.electric_plug
  | "desktop_computer" -> Emoji.desktop_computer
  | "printer" -> Emoji.printer
  | "keyboard" -> Emoji.keyboard
  | "computer_mouse" -> Emoji.computer_mouse
  | "trackball" -> Emoji.trackball
  | "computer_disk" -> Emoji.computer_disk
  | "floppy_disk" -> Emoji.floppy_disk
  | "optical_disk" -> Emoji.optical_disk
  | "dvd" -> Emoji.dvd
  | "movie_camera" -> Emoji.movie_camera
  | "film_frames" -> Emoji.film_frames
  | "film_projector" -> Emoji.film_projector
  | "clapper_board" -> Emoji.clapper_board
  | "television" -> Emoji.television
  | "camera" -> Emoji.camera
  | "camera_with_flash" -> Emoji.camera_with_flash
  | "video_camera" -> Emoji.video_camera
  | "videocassette" -> Emoji.videocassette
  | "candle" -> Emoji.candle
  | "light_bulb" -> Emoji.light_bulb
  | "flashlight" -> Emoji.flashlight
  | "red_paper_lantern" -> Emoji.red_paper_lantern
  | "notebook_with_decorative_cover" -> Emoji.notebook_with_decorative_cover
  | "closed_book" -> Emoji.closed_book
  | "open_book" -> Emoji.open_book
  | "green_book" -> Emoji.green_book
  | "blue_book" -> Emoji.blue_book
  | "orange_book" -> Emoji.orange_book
  | "books" -> Emoji.books
  | "notebook" -> Emoji.notebook
  | "ledger" -> Emoji.ledger
  | "page_with_curl" -> Emoji.page_with_curl
  | "scroll" -> Emoji.scroll
  | "page_facing_up" -> Emoji.page_facing_up
  | "newspaper" -> Emoji.newspaper
  | "bookmark_tabs" -> Emoji.bookmark_tabs
  | "bookmark" -> Emoji.bookmark
  | "label" -> Emoji.label
  | "money_bag" -> Emoji.money_bag
  | "yen_banknote" -> Emoji.yen_banknote
  | "dollar_banknote" -> Emoji.dollar_banknote
  | "euro_banknote" -> Emoji.euro_banknote
  | "pound_banknote" -> Emoji.pound_banknote
  | "money_with_wings" -> Emoji.money_with_wings
  | "credit_card" -> Emoji.credit_card
  | "chart_increasing_with_yen" -> Emoji.chart_increasing_with_yen
  | "currency_exchange" -> Emoji.currency_exchange
  | "heavy_dollar_sign" -> Emoji.heavy_dollar_sign
  | "envelope" -> Emoji.envelope
  | "incoming_envelope" -> Emoji.incoming_envelope
  | "envelope_with_arrow" -> Emoji.envelope_with_arrow
  | "outbox_tray" -> Emoji.outbox_tray
  | "inbox_tray" -> Emoji.inbox_tray
  | "package" -> Emoji.package
  | "closed_mailbox_with_raised_flag" -> Emoji.closed_mailbox_with_raised_flag
  | "closed_mailbox_with_lowered_flag" -> 
    Emoji.closed_mailbox_with_lowered_flag
  | "open_mailbox_with_raised_flag" -> Emoji.open_mailbox_with_raised_flag
  | "open_mailbox_with_lowered_flag" -> Emoji.open_mailbox_with_lowered_flag
  | "postbox" -> Emoji.postbox
  | "ballot_box_with_ballot" -> Emoji.ballot_box_with_ballot
  | "pencil" -> Emoji.pencil
  | "black_nib" -> Emoji.black_nib
  | "fountain_pen" -> Emoji.fountain_pen
  | "pen" -> Emoji.pen
  | "paintbrush" -> Emoji.paintbrush
  | "crayon" -> Emoji.crayon
  | "memo" -> Emoji.memo
  | "briefcase" -> Emoji.briefcase
  | "file_folder" -> Emoji.file_folder
  | "open_file_folder" -> Emoji.open_file_folder
  | "card_index_dividers" -> Emoji.card_index_dividers
  | "calendar" -> Emoji.calendar
  | "spiral_notepad" -> Emoji.spiral_notepad
  | "spiral_calendar" -> Emoji.spiral_calendar
  | "card_index" -> Emoji.card_index
  | "chart_increasing" -> Emoji.chart_increasing
  | "chart_decreasing" -> Emoji.chart_decreasing
  | "bar_chart" -> Emoji.bar_chart
  | "clipboard" -> Emoji.clipboard
  | "pushpin" -> Emoji.pushpin
  | "round_pushpin" -> Emoji.round_pushpin
  | "paperclip" -> Emoji.paperclip
  | "linked_paperclips" -> Emoji.linked_paperclips
  | "straight_ruler" -> Emoji.straight_ruler
  | "triangular_ruler" -> Emoji.triangular_ruler
  | "scissors" -> Emoji.scissors
  | "card_file_box" -> Emoji.card_file_box
  | "file_cabinet" -> Emoji.file_cabinet
  | "wastebasket" -> Emoji.wastebasket
  | "locked" -> Emoji.locked
  | "unlocked" -> Emoji.unlocked
  | "locked_with_pen" -> Emoji.locked_with_pen
  | "locked_with_key" -> Emoji.locked_with_key
  | "key" -> Emoji.key
  | "old_key" -> Emoji.old_key
  | "hammer" -> Emoji.hammer
  | "pick" -> Emoji.pick
  | "hammer_and_pick" -> Emoji.hammer_and_pick
  | "hammer_and_wrench" -> Emoji.hammer_and_wrench
  | "dagger" -> Emoji.dagger
  | "crossed_swords" -> Emoji.crossed_swords
  | "pistol" -> Emoji.pistol
  | "bow_and_arrow" -> Emoji.bow_and_arrow
  | "shield" -> Emoji.shield
  | "wrench" -> Emoji.wrench
  | "nut_and_bolt" -> Emoji.nut_and_bolt
  | "gear" -> Emoji.gear
  | "clamp" -> Emoji.clamp
  | "balance_scale" -> Emoji.balance_scale
  | "link" -> Emoji.link
  | "chains" -> Emoji.chains
  | "door" -> Emoji.door
  | "bed" -> Emoji.bed
  | "couch_and_lamp" -> Emoji.couch_and_lamp
  | "toilet" -> Emoji.toilet
  | "shower" -> Emoji.shower
  | "bathtub" -> Emoji.bathtub
  | "passport_control" -> Emoji.passport_control
  | "customs" -> Emoji.customs
  | "baggage_claim" -> Emoji.baggage_claim
  | "left_luggage" -> Emoji.left_luggage
  | "warning" -> Emoji.warning
  | "children_crossing" -> Emoji.children_crossing
  | "no_entry" -> Emoji.no_entry
  | "prohibited" -> Emoji.prohibited
  | "no_bicycles" -> Emoji.no_bicycles
  | "no_smoking" -> Emoji.no_smoking
  | "no_littering" -> Emoji.no_littering
  | "no_pedestrians" -> Emoji.no_pedestrians
  | "no_mobile_phones" -> Emoji.no_mobile_phones
  | "no_one_under_eighteen" -> Emoji.no_one_under_eighteen
  | "radioactive" -> Emoji.radioactive
  | "biohazard" -> Emoji.biohazard
  | "up_arrow" -> Emoji.up_arrow
  | "up-right_arrow" -> Emoji.up_right_arrow
  | "right_arrow" -> Emoji.right_arrow
  | "down-right_arrow" -> Emoji.down_right_arrow
  | "down_arrow" -> Emoji.down_arrow
  | "down-left_arrow" -> Emoji.down_left_arrow
  | "left_arrow" -> Emoji.left_arrow
  | "up-left_arrow" -> Emoji.up_left_arrow
  | "up-down_arrow" -> Emoji.up_down_arrow
  | "left-right_arrow" -> Emoji.left_right_arrow
  | "right_arrow_curving_left" -> Emoji.right_arrow_curving_left
  | "left_arrow_curving_right" -> Emoji.left_arrow_curving_right
  | "right_arrow_curving_up" -> Emoji.right_arrow_curving_up
  | "right_arrow_curving_down" -> Emoji.right_arrow_curving_down
  | "clockwise_vertical_arrows" -> Emoji.clockwise_vertical_arrows
  | "back_arrow" -> Emoji.back_arrow
  | "end_arrow" -> Emoji.end_arrow
  | "soon_arrow" -> Emoji.soon_arrow
  | "top_arrow" -> Emoji.top_arrow
  | "place_of_worship" -> Emoji.place_of_worship
  | "atom_symbol" -> Emoji.atom_symbol
  | "om" -> Emoji.om
  | "star_of_david" -> Emoji.star_of_david
  | "wheel_of_dharma" -> Emoji.wheel_of_dharma
  | "yin_yang" -> Emoji.yin_yang
  | "latin_cross" -> Emoji.latin_cross
  | "orthodox_cross" -> Emoji.orthodox_cross
  | "star_and_crescent" -> Emoji.star_and_crescent
  | "peace_symbol" -> Emoji.peace_symbol
  | "menorah" -> Emoji.menorah
  | "aries" -> Emoji.aries
  | "taurus" -> Emoji.taurus
  | "gemini" -> Emoji.gemini
  | "cancer" -> Emoji.cancer
  | "leo" -> Emoji.leo
  | "virgo" -> Emoji.virgo
  | "libra" -> Emoji.libra
  | "sagittarius" -> Emoji.sagittarius
  | "capricorn" -> Emoji.capricorn
  | "aquarius" -> Emoji.aquarius
  | "pisces" -> Emoji.pisces
  | "ophiuchus" -> Emoji.ophiuchus
  | "shuffle_tracks_button" -> Emoji.shuffle_tracks_button
  | "repeat_button" -> Emoji.repeat_button
  | "repeat_single_button" -> Emoji.repeat_single_button
  | "play_button" -> Emoji.play_button
  | "fast-forward_button" -> Emoji.fast_forward_button
  | "next_track_button" -> Emoji.next_track_button
  | "play_or_pause_button" -> Emoji.play_or_pause_button
  | "reverse_button" -> Emoji.reverse_button
  | "fast_reverse_button" -> Emoji.fast_reverse_button
  | "last_track_button" -> Emoji.last_track_button
  | "fast_up_button" -> Emoji.fast_up_button
  | "fast_down_button" -> Emoji.fast_down_button
  | "pause_button" -> Emoji.pause_button
  | "stop_button" -> Emoji.stop_button
  | "record_button" -> Emoji.record_button
  | "eject_button" -> Emoji.eject_button
  | "cinema" -> Emoji.cinema
  | "dim_button" -> Emoji.dim_button
  | "bright_button" -> Emoji.bright_button
  | "antenna_bars" -> Emoji.antenna_bars
  | "vibration_mode" -> Emoji.vibration_mode
  | "mobile_phone_off" -> Emoji.mobile_phone_off
  | "female_sign" -> Emoji.female_sign
  | "male_sign" -> Emoji.male_sign
  | "medical_symbol" -> Emoji.medical_symbol
  | "recycling_symbol" -> Emoji.recycling_symbol
  | "trident_emblem" -> Emoji.trident_emblem
  | "name_badge" -> Emoji.name_badge
  | "japanese_symbol_for_beginner" -> Emoji.japanese_symbol_for_beginner
  | "double_exclamation_mark" -> Emoji.double_exclamation_mark
  | "exclamation_question_mark" -> Emoji.exclamation_question_mark
  | "question_mark" -> Emoji.question_mark
  | "white_question_mark" -> Emoji.white_question_mark
  | "white_exclamation_mark" -> Emoji.white_exclamation_mark
  | "exclamation_mark" -> Emoji.exclamation_mark
  | "wavy_dash" -> Emoji.wavy_dash
  | "copyright" -> Emoji.copyright
  | "registered" -> Emoji.registered
  | "trade_mark" -> Emoji.trade_mark
  | "input_latin_uppercase" -> Emoji.input_latin_uppercase
  | "input_latin_lowercase" -> Emoji.input_latin_lowercase
  | "input_numbers" -> Emoji.input_numbers
  | "input_symbols" -> Emoji.input_symbols
  | "input_latin_letters" -> Emoji.input_latin_letters
  | "cl_button" -> Emoji.cl_button
  | "cool_button" -> Emoji.cool_button
  | "free_button" -> Emoji.free_button
  | "information" -> Emoji.information
  | "id_button" -> Emoji.id_button
  | "circled_m" -> Emoji.circled_m
  | "new_button" -> Emoji.new_button
  | "ng_button" -> Emoji.ng_button
  | "ok_button" -> Emoji.ok_button
  | "p_button" -> Emoji.p_button
  | "sos_button" -> Emoji.sos_button
  | "vs_button" -> Emoji.vs_button
  | "japanese_“here”_button" -> Emoji.japanese_here_button
  | "japanese_“service_charge”_button" -> Emoji.japanese_service_charge_button
  | "japanese_“monthly_amount”_button" -> Emoji.japanese_monthly_amount_button
  | "japanese_“not_free_of_charge”_button" -> 
    Emoji.japanese_not_free_of_charge_button
  | "japanese_“reserved”_button" -> Emoji.japanese_reserved_button
  | "japanese_“bargain”_button" -> Emoji.japanese_bargain_button
  | "japanese_“discount”_button" -> Emoji.japanese_discount_button
  | "japanese_“free_of_charge”_button" -> Emoji.japanese_free_of_charge_button
  | "japanese_“prohibited”_button" -> Emoji.japanese_prohibited_button
  | "japanese_“acceptable”_button" -> Emoji.japanese_acceptable_button
  | "japanese_“application”_button" -> Emoji.japanese_application_button
  | "japanese_“passing_grade”_button" -> Emoji.japanese_passing_grade_button
  | "japanese_“vacancy”_button" -> Emoji.japanese_vacancy_button
  | "japanese_“congratulations”_button" -> 
    Emoji.japanese_congratulations_button
  | "japanese_“secret”_button" -> Emoji.japanese_secret_button
  | "japanese_“open_for_business”_button" ->
    Emoji.japanese_open_for_business_button
  | "japanese_“no_vacancy”_button" -> Emoji.japanese_no_vacancy_button
  | "red_circle" -> Emoji.red_circle
  | "white_circle" -> Emoji.white_circle
  | "black_large_square" -> Emoji.black_large_square
  | "white_large_square" -> Emoji.white_large_square
  | "black_medium_square" -> Emoji.black_medium_square
  | "white_medium_square" -> Emoji.white_medium_square
  | "black_medium-small_square" -> Emoji.black_medium_small_square
  | "white_medium-small_square" -> Emoji.white_medium_small_square
  | "black_small_square" -> Emoji.black_small_square
  | "white_small_square" -> Emoji.white_small_square
  | "large_orange_diamond" -> Emoji.large_orange_diamond
  | "large_blue_diamond" -> Emoji.large_blue_diamond
  | "small_orange_diamond" -> Emoji.small_orange_diamond
  | "small_blue_diamond" -> Emoji.small_blue_diamond
  | "red_triangle_pointed_up" -> Emoji.red_triangle_pointed_up
  | "red_triangle_pointed_down" -> Emoji.red_triangle_pointed_down
  | "diamond_with_a_dot" -> Emoji.diamond_with_a_dot
  | "radio_button" -> Emoji.radio_button
  | "white_square_button" -> Emoji.white_square_button
  | "black_square_button" -> Emoji.black_square_button
  | "chequered_flag" -> Emoji.chequered_flag
  | "triangular_flag" -> Emoji.triangular_flag
  | "crossed_flags" -> Emoji.crossed_flags
  | "black_flag" -> Emoji.black_flag
  | "white_flag" -> Emoji.white_flag
  | "rainbow_flag" -> Emoji.rainbow_flag
  | "flag:_ascension_island" -> Emoji.ascension_island
  | "flag:_andorra" -> Emoji.andorra
  | "flag:_united_arab_emirates" -> Emoji.united_arab_emirates
  | "flag:_afghanistan" -> Emoji.afghanistan
  | "flag:_antigua_&_barbuda" -> Emoji.antigua_and_barbuda
  | "flag:_anguilla" -> Emoji.anguilla
  | "flag:_albania" -> Emoji.albania
  | "flag:_armenia" -> Emoji.armenia
  | "flag:_angola" -> Emoji.angola
  | "flag:_antarctica" -> Emoji.antarctica
  | "flag:_argentina" -> Emoji.argentina
  | "flag:_american_samoa" -> Emoji.american_samoa
  | "flag:_austria" -> Emoji.austria
  | "flag:_australia" -> Emoji.australia
  | "flag:_aruba" -> Emoji.aruba
  | "flag:_azerbaijan" -> Emoji.azerbaijan
  | "flag:_bosnia_&_herzegovina" -> Emoji.bosnia_and_herzegovina
  | "flag:_barbados" -> Emoji.barbados
  | "flag:_bangladesh" -> Emoji.bangladesh
  | "flag:_belgium" -> Emoji.belgium
  | "flag:_burkina_faso" -> Emoji.burkina_faso
  | "flag:_bulgaria" -> Emoji.bulgaria
  | "flag:_bahrain" -> Emoji.bahrain
  | "flag:_burundi" -> Emoji.burundi
  | "flag:_benin" -> Emoji.benin
  | "flag:_bermuda" -> Emoji.bermuda
  | "flag:_brunei" -> Emoji.brunei
  | "flag:_bolivia" -> Emoji.bolivia
  | "flag:_caribbean_netherlands" -> Emoji.caribbean_netherlands
  | "flag:_brazil" -> Emoji.brazil
  | "flag:_bahamas" -> Emoji.bahamas
  | "flag:_bhutan" -> Emoji.bhutan
  | "flag:_bouvet_island" -> Emoji.bouvet_island
  | "flag:_botswana" -> Emoji.botswana
  | "flag:_belarus" -> Emoji.belarus
  | "flag:_belize" -> Emoji.belize
  | "flag:_canada" -> Emoji.canada
  | "flag:_central_african_republic" -> Emoji.central_african_republic
  | "flag:_switzerland" -> Emoji.switzerland
  | "flag:_cook_islands" -> Emoji.cook_islands
  | "flag:_chile" -> Emoji.chile
  | "flag:_cameroon" -> Emoji.cameroon
  | "flag:_china" -> Emoji.china
  | "flag:_colombia" -> Emoji.colombia
  | "flag:_clipperton_island" -> Emoji.clipperton_island
  | "flag:_costa_rica" -> Emoji.costa_rica
  | "flag:_cuba" -> Emoji.cuba
  | "flag:_cape_verde" -> Emoji.cape_verde
  | "flag:_christmas_island" -> Emoji.christmas_island
  | "flag:_cyprus" -> Emoji.cyprus
  | "flag:_germany" -> Emoji.germany
  | "flag:_diego_garcia" -> Emoji.diego_garcia
  | "flag:_djibouti" -> Emoji.djibouti
  | "flag:_denmark" -> Emoji.denmark
  | "flag:_dominica" -> Emoji.dominica
  | "flag:_dominican_republic" -> Emoji.dominican_republic
  | "flag:_algeria" -> Emoji.algeria
  | "flag:_ceuta_&_melilla" -> Emoji.ceuta_and_melilla
  | "flag:_ecuador" -> Emoji.ecuador
  | "flag:_estonia" -> Emoji.estonia
  | "flag:_egypt" -> Emoji.egypt
  | "flag:_western_sahara" -> Emoji.western_sahara
  | "flag:_eritrea" -> Emoji.eritrea
  | "flag:_spain" -> Emoji.spain
  | "flag:_ethiopia" -> Emoji.ethiopia
  | "flag:_european_union" -> Emoji.european_union
  | "flag:_finland" -> Emoji.finland
  | "flag:_fiji" -> Emoji.fiji
  | "flag:_falkland_islands" -> Emoji.falkland_islands
  | "flag:_micronesia" -> Emoji.micronesia
  | "flag:_faroe_islands" -> Emoji.faroe_islands
  | "flag:_france" -> Emoji.france
  | "flag:_gabon" -> Emoji.gabon
  | "flag:_united_kingdom" -> Emoji.united_kingdom
  | "flag:_grenada" -> Emoji.grenada
  | "flag:_georgia" -> Emoji.georgia
  | "flag:_french_guiana" -> Emoji.french_guiana
  | "flag:_guernsey" -> Emoji.guernsey
  | "flag:_ghana" -> Emoji.ghana
  | "flag:_gibraltar" -> Emoji.gibraltar
  | "flag:_greenland" -> Emoji.greenland
  | "flag:_gambia" -> Emoji.gambia
  | "flag:_guinea" -> Emoji.guinea
  | "flag:_guadeloupe" -> Emoji.guadeloupe
  | "flag:_equatorial_guinea" -> Emoji.equatorial_guinea
  | "flag:_greece" -> Emoji.greece
  | "flag:_south_georgia_&_south_sandwich_islands" ->
    Emoji.south_georgia_and_south_sandwich_islands
  | "flag:_guatemala" -> Emoji.guatemala
  | "flag:_guam" -> Emoji.guam
  | "flag:_guinea-bissau" -> Emoji.guinea_bissau
  | "flag:_guyana" -> Emoji.guyana
  | "flag:_hong_kong_sar_china" -> Emoji.hong_kong_sar_china
  | "flag:_heard_&_mcdonald_islands" -> Emoji.heard_and_mcdonald_islands
  | "flag:_honduras" -> Emoji.honduras
  | "flag:_croatia" -> Emoji.croatia
  | "flag:_haiti" -> Emoji.haiti
  | "flag:_hungary" -> Emoji.hungary
  | "flag:_canary_islands" -> Emoji.canary_islands
  | "flag:_indonesia" -> Emoji.indonesia
  | "flag:_ireland" -> Emoji.ireland
  | "flag:_israel" -> Emoji.israel
  | "flag:_isle_of_man" -> Emoji.isle_of_man
  | "flag:_india" -> Emoji.india
  | "flag:_british_indian_ocean_territory" -> 
    Emoji.british_indian_ocean_territory
  | "flag:_iraq" -> Emoji.iraq
  | "flag:_iran" -> Emoji.iran
  | "flag:_iceland" -> Emoji.iceland
  | "flag:_italy" -> Emoji.italy
  | "flag:_jersey" -> Emoji.jersey
  | "flag:_jamaica" -> Emoji.jamaica
  | "flag:_jordan" -> Emoji.jordan
  | "flag:_japan" -> Emoji.japan
  | "flag:_kenya" -> Emoji.kenya
  | "flag:_kyrgyzstan" -> Emoji.kyrgyzstan
  | "flag:_cambodia" -> Emoji.cambodia
  | "flag:_kiribati" -> Emoji.kiribati
  | "flag:_comoros" -> Emoji.comoros
  | "flag:_north_korea" -> Emoji.north_korea
  | "flag:_south_korea" -> Emoji.south_korea
  | "flag:_kuwait" -> Emoji.kuwait
  | "flag:_cayman_islands" -> Emoji.cayman_islands
  | "flag:_kazakhstan" -> Emoji.kazakhstan
  | "flag:_laos" -> Emoji.laos
  | "flag:_lebanon" -> Emoji.lebanon
  | "flag:_liechtenstein" -> Emoji.liechtenstein
  | "flag:_sri_lanka" -> Emoji.sri_lanka
  | "flag:_liberia" -> Emoji.liberia
  | "flag:_lesotho" -> Emoji.lesotho
  | "flag:_lithuania" -> Emoji.lithuania
  | "flag:_luxembourg" -> Emoji.luxembourg
  | "flag:_latvia" -> Emoji.latvia
  | "flag:_libya" -> Emoji.libya
  | "flag:_morocco" -> Emoji.morocco
  | "flag:_monaco" -> Emoji.monaco
  | "flag:_moldova" -> Emoji.moldova
  | "flag:_montenegro" -> Emoji.montenegro
  | "flag:_madagascar" -> Emoji.madagascar
  | "flag:_marshall_islands" -> Emoji.marshall_islands
  | "flag:_mali" -> Emoji.mali
  | "flag:_mongolia" -> Emoji.mongolia
  | "flag:_macao_sar_china" -> Emoji.macau_sar_china
  | "flag:_northern_mariana_islands" -> Emoji.northern_mariana_islands
  | "flag:_martinique" -> Emoji.martinique
  | "flag:_mauritania" -> Emoji.mauritania
  | "flag:_montserrat" -> Emoji.montserrat
  | "flag:_malta" -> Emoji.malta
  | "flag:_mauritius" -> Emoji.mauritius
  | "flag:_maldives" -> Emoji.maldives
  | "flag:_malawi" -> Emoji.malawi
  | "flag:_mexico" -> Emoji.mexico
  | "flag:_malaysia" -> Emoji.malaysia
  | "flag:_mozambique" -> Emoji.mozambique
  | "flag:_namibia" -> Emoji.namibia
  | "flag:_new_caledonia" -> Emoji.new_caledonia
  | "flag:_niger" -> Emoji.niger
  | "flag:_norfolk_island" -> Emoji.norfolk_island
  | "flag:_nigeria" -> Emoji.nigeria
  | "flag:_nicaragua" -> Emoji.nicaragua
  | "flag:_netherlands" -> Emoji.netherlands
  | "flag:_norway" -> Emoji.norway
  | "flag:_nepal" -> Emoji.nepal
  | "flag:_nauru" -> Emoji.nauru
  | "flag:_niue" -> Emoji.niue
  | "flag:_new_zealand" -> Emoji.new_zealand
  | "flag:_oman" -> Emoji.oman
  | "flag:_panama" -> Emoji.panama
  | "flag:_peru" -> Emoji.peru
  | "flag:_french_polynesia" -> Emoji.french_polynesia
  | "flag:_papua_new_guinea" -> Emoji.papua_new_guinea
  | "flag:_philippines" -> Emoji.philippines
  | "flag:_pakistan" -> Emoji.pakistan
  | "flag:_poland" -> Emoji.poland
  | "flag:_pitcairn_islands" -> Emoji.pitcairn_islands
  | "flag:_puerto_rico" -> Emoji.puerto_rico
  | "flag:_palestinian_territories" -> Emoji.palestinian_territories
  | "flag:_portugal" -> Emoji.portugal
  | "flag:_palau" -> Emoji.palau
  | "flag:_paraguay" -> Emoji.paraguay
  | "flag:_qatar" -> Emoji.qatar
  | "flag:_romania" -> Emoji.romania
  | "flag:_serbia" -> Emoji.serbia
  | "flag:_russia" -> Emoji.russia
  | "flag:_rwanda" -> Emoji.rwanda
  | "flag:_saudi_arabia" -> Emoji.saudi_arabia
  | "flag:_solomon_islands" -> Emoji.solomon_islands
  | "flag:_seychelles" -> Emoji.seychelles
  | "flag:_sudan" -> Emoji.sudan
  | "flag:_sweden" -> Emoji.sweden
  | "flag:_singapore" -> Emoji.singapore
  | "flag:_slovenia" -> Emoji.slovenia
  | "flag:_slovakia" -> Emoji.slovakia
  | "flag:_sierra_leone" -> Emoji.sierra_leone
  | "flag:_san_marino" -> Emoji.san_marino
  | "flag:_senegal" -> Emoji.senegal
  | "flag:_somalia" -> Emoji.somalia
  | "flag:_suriname" -> Emoji.suriname
  | "flag:_south_sudan" -> Emoji.south_sudan
  | "flag:_el_salvador" -> Emoji.el_salvador
  | "flag:_sint_maarten" -> Emoji.sint_maarten
  | "flag:_syria" -> Emoji.syria
  | "flag:_tristan_da_cunha" -> Emoji.tristan_da_cunha
  | "flag:_chad" -> Emoji.chad
  | "flag:_french_southern_territories" -> 
    Emoji.french_southern_territories
  | "flag:_togo" -> Emoji.togo
  | "flag:_thailand" -> Emoji.thailand
  | "flag:_tajikistan" -> Emoji.tajikistan
  | "flag:_tokelau" -> Emoji.tokelau
  | "flag:_turkmenistan" -> Emoji.turkmenistan
  | "flag:_tunisia" -> Emoji.tunisia
  | "flag:_tonga" -> Emoji.tonga
  | "flag:_turkey" -> Emoji.turkey
  | "flag:_tuvalu" -> Emoji.tuvalu
  | "flag:_taiwan" -> Emoji.taiwan
  | "flag:_tanzania" -> Emoji.tanzania
  | "flag:_ukraine" -> Emoji.ukraine
  | "flag:_uganda" -> Emoji.uganda
  | "flag:_united_nations" -> Emoji.united_nations
  | "flag:_united_states" -> Emoji.united_states
  | "flag:_uruguay" -> Emoji.uruguay
  | "flag:_uzbekistan" -> Emoji.uzbekistan
  | "flag:_vatican_city" -> Emoji.vatican_city
  | "flag:_venezuela" -> Emoji.venezuela
  | "flag:_british_virgin_islands" -> Emoji.british_virgin_islands
  | "flag:_vietnam" -> Emoji.vietnam
  | "flag:_vanuatu" -> Emoji.vanuatu
  | "flag:_samoa" -> Emoji.samoa
  | "flag:_kosovo" -> Emoji.kosovo
  | "flag:_yemen" -> Emoji.yemen
  | "flag:_mayotte" -> Emoji.mayotte
  | "flag:_south_africa" -> Emoji.south_africa
  | "flag:_zambia" -> Emoji.zambia
  | "flag:_zimbabwe" -> Emoji.zimbabwe
  | _ -> Emoji.question_mark