#!/bin/sh
# File generated by ocamlbuild

cd '/Users/oscarso/Desktop/All Folders/Sophomore Sem 1/CS 3110/CS3110-Final-Project'

rm -f encryption.cmi
rm -f encryption.cmx
rm -f encryption.o
rm -f oscartest.cmi
rm -f oscartest.cmx
rm -f oscartest.o
# Also clean the script itself
rm -f '/Users/oscarso/Desktop/All Folders/Sophomore Sem 1/CS 3110/CS3110-Final-Project/_build/sanitize.sh'
